# Generated by Django 3.1.2 on 2021-03-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Adviser',
        ),
    ]
